In [5]:
#996 (Original data - no fingerprints)
%run data_utils.py
%run train.py

Using default parameters.
(133885, 3)
(133885, 20)
(133885, 3)
Successfully created train/val data file in data\F99_6data_train_val.
Successfully created test data file in data\F99_6data_test.
INFO:tensorflow:Using config: {'_model_dir': 'results\\996', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E2AF04B908>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
One train episode equals 100 normal epochs and 1 penalty

INFO:tensorflow:Saving dict for global step 650: eval_accuracy = 0.0020833334, global_step = 650, loss = 17.5998
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 650: results\996\model.ckpt-650
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-06-12T22:03:08Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\996\model.ckpt-650
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2019-06-12-22:03:09
INFO:tensorflow:Saving dict for global step 650: eval_accuracy = 0.004166667, global_step = 650, loss = 9.103604
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 650: results\996\model.ckpt-650
Model evaluated. Results:
 {'val_error': 17.5998, 'complexity': 10, 'extr_error': 9.103604, 'id': 996}


In [2]:
#995
%run data_utils.py
%run train.py

Using default parameters.
(133247, 3)
(133247, 20)
Successfully created train/val data file in data\F99_5data_train_val.
Successfully created test data file in data\F99_5data_test.
INFO:tensorflow:Using config: {'_model_dir': 'results\\995', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001F9978669B0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
One train episode equals 100 normal epochs and 1 penalty epoch.
Trai

NanLossDuringTrainingError: NaN loss during training.

In [1]:
#994 (2 layers)
%run data_utils.py
%run train.py

Using default parameters.
(133247, 39)
(133247, 20)
Successfully created train/val data file in data\F99_4data_train_val.
Successfully created test data file in data\F99_4data_test.
INFO:tensorflow:Using config: {'_model_dir': 'results\\994', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000017E73CC1F98>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
One train episode equals 100 normal epochs and 1 penalty epoch.
Tra

In [4]:
%run train.py#993

INFO:tensorflow:Using config: {'_model_dir': 'results\\993', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001D739E825C0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


One train episode equals 100 normal epochs and 1 penalty epoch.
Train episode: 1 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-86140
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 86140 into results\993\model.ckpt.
INFO:tensorflow:loss = 5.714408, step = 86141
INFO:tensorflow:Saving checkpoints for 86226 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.8464447.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-86226
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 86226 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.086333334
INFO:tensorflow:loss = 

Train episode: 2 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-94754
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 94754 into results\993\model.ckpt.
INFO:tensorflow:loss = 4.356815, step = 94755
INFO:tensorflow:Saving checkpoints for 94840 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 8.911765.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-94840
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 94840 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.094
INFO:tensorflow:loss = 0.16796

Train episode: 3 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-103368
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 103368 into results\993\model.ckpt.
INFO:tensorflow:loss = 3.5432482, step = 103369
INFO:tensorflow:Saving checkpoints for 103454 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-103454
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 103454 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10233333
INFO:tensorflow:loss = 

Train episode: 4 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-111982
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 111982 into results\993\model.ckpt.
INFO:tensorflow:loss = 1.6785226, step = 111983
INFO:tensorflow:Saving checkpoints for 112068 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-112068
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 112068 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10733333
INFO:tensorflow:loss = 

Train episode: 5 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-120596
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 120596 into results\993\model.ckpt.
INFO:tensorflow:loss = 5.8717723, step = 120597
INFO:tensorflow:Saving checkpoints for 120682 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 2.9883995.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-120682
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 120682 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.104
INFO:tensorflow:loss =

Train episode: 6 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-129210
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 129210 into results\993\model.ckpt.
INFO:tensorflow:loss = 1.755258, step = 129211
INFO:tensorflow:Saving checkpoints for 129296 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-129296
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 129296 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10366666
INFO:tensorflow:loss = 0

Train episode: 7 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-137824
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 137824 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.2014124, step = 137825
INFO:tensorflow:Saving checkpoints for 137910 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-137910
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 137910 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10566667
INFO:tensorflow:loss = 

Train episode: 8 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-146438
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 146438 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.822619, step = 146439
INFO:tensorflow:Saving checkpoints for 146524 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-146524
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 146524 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10733333
INFO:tensorflow:loss = 0

Train episode: 9 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-155052
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 155052 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.4306033, step = 155053
INFO:tensorflow:Saving checkpoints for 155138 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-155138
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 155138 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.11333334
INFO:tensorflow:loss = 

Train episode: 10 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-163666
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 163666 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.0, step = 163667
INFO:tensorflow:Saving checkpoints for 163752 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-163752
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 163752 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10933334
INFO:tensorflow:loss = 0.0609

Training complete. Evaluating...


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-06-06T19:21:57Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-172280
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


KeyboardInterrupt: 

In [8]:
%run train.py 
#993

INFO:tensorflow:Using config: {'_model_dir': 'results\\993', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001D713F9F9B0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


One train episode equals 100 normal epochs and 1 penalty epoch.
Train episode: 1 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-172280
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 172280 into results\993\model.ckpt.
INFO:tensorflow:loss = 22.12839, step = 172281
INFO:tensorflow:Saving checkpoints for 172366 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-172366
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 172366 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.116
INFO:tensorflow:loss = 0.0594

Train episode: 2 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-180894
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 180894 into results\993\model.ckpt.
INFO:tensorflow:loss = 9.842793, step = 180895
INFO:tensorflow:Saving checkpoints for 180980 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-180980
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 180980 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10166667
INFO:tensorflow:loss = 0

Train episode: 3 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-189508
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 189508 into results\993\model.ckpt.
INFO:tensorflow:loss = 7.6110754, step = 189509
INFO:tensorflow:Saving checkpoints for 189594 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-189594
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 189594 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.105333336
INFO:tensorflow:loss =

Train episode: 4 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-198122
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 198122 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.6504936, step = 198123
INFO:tensorflow:Saving checkpoints for 198208 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.3265675.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-198208
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 198208 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10633333
INFO:tensorflow:l

Train episode: 5 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-206736
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 206736 into results\993\model.ckpt.
INFO:tensorflow:loss = 2.10736, step = 206737
INFO:tensorflow:Saving checkpoints for 206822 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-206822
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 206822 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.101
INFO:tensorflow:loss = 0.06137

Train episode: 6 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-215350
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 215350 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.0, step = 215351
INFO:tensorflow:Saving checkpoints for 215436 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-215436
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 215436 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.106
INFO:tensorflow:loss = 0.057369947

Train episode: 7 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-223964
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 223964 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.0, step = 223965
INFO:tensorflow:Saving checkpoints for 224050 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-224050
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 224050 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.12433334
INFO:tensorflow:loss = 0.0547

Train episode: 8 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-232578
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 232578 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.0, step = 232579
INFO:tensorflow:Saving checkpoints for 232664 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-232664
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 232664 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.112333335
INFO:tensorflow:loss = 0.057

Train episode: 9 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-241192
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 241192 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.26294604, step = 241193
INFO:tensorflow:Saving checkpoints for 241278 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-241278
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 241278 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.102
INFO:tensorflow:loss = 0.05

Train episode: 10 out of 60.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-249806
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 249806 into results\993\model.ckpt.
INFO:tensorflow:loss = 0.0, step = 249807
INFO:tensorflow:Saving checkpoints for 249892 into results\993\model.ckpt.
INFO:tensorflow:Loss for final step: 4.436961.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-249892
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 249892 into results\993\model.ckpt.
INFO:tensorflow:train_accuracy = 0.10266667
INFO:tensorflow:loss = 0

Training complete. Evaluating...


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-06-06T22:09:53Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\993\model.ckpt-258420
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


KeyboardInterrupt: 

In [29]:
%run data_utils.py


Using default parameters.
(133247, 39)
(133247, 20)
(array([[ 1.20110000e+01, -2.18263367e-01,  2.84422679e+00, ...,
        -1.81257675e+00, -3.67729567e+00,  1.16848682e+00],
       [ 1.20110000e+01,  1.48343501e-01,  3.00164098e+00, ...,
         1.40813654e+00, -2.48173163e+00, -2.54135646e+00],
       [ 1.59990000e+01,  2.27334053e-01,  2.51522547e+00, ...,
         9.40558973e-02, -1.31592492e+00,  7.77500821e-02],
       ...,
       [ 1.20110000e+01,  3.53378785e-02,  2.40410958e+00, ...,
        -2.19362082e+00, -2.73963420e+00,  4.12943700e-01],
       [ 1.20110000e+01, -1.54957542e-02,  2.83553405e+00, ...,
         4.55031954e-02, -2.13270268e+00, -1.87481927e-01],
       [ 1.20110000e+01, -2.76655905e-01,  3.00182995e+00, ...,
         1.70740852e+00, -4.30207463e+00,  3.51664026e+00]]), array([[3.01814, 1.08662, 1.00845],
       [3.83256, 1.06166, 0.88244],
       [9.81669, 3.7809 , 2.7296 ],
       ...,
       [2.16817, 1.46866, 1.07722],
       [3.12217, 1.38775, 0.96748

In [32]:
#991
%run train.py

INFO:tensorflow:Using config: {'_model_dir': 'results\\991', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001A479D40780>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
One train episode equals 100 normal epochs and 1 penalty epoch.
Train episode: 1 out of 60.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INF

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\991\model.ckpt-111982
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 111982 into results\991\model.ckpt.
INFO:tensorflow:loss = 0.0, step = 111983
INFO:tensorflow:Saving checkpoints for 112068 into results\991\model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\991\model.ckpt-112068
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 112068 into results\991\model.ckpt.
INFO:tensorflow:train_accuracy = 0.061
INFO:tensorflow:loss = 0.34230828, step = 112069
INFO:tensorflow:global_step/sec: 34.7392
INFO:tensorflow:t

INFO:tensorflow:loss = 7.0795555, step = 137911
INFO:tensorflow:global_step/sec: 35.9778
INFO:tensorflow:train_accuracy = 0.058166668 (27.795 sec)
INFO:tensorflow:loss = 0.6848564, step = 138911 (27.795 sec)
INFO:tensorflow:global_step/sec: 39.8285
INFO:tensorflow:train_accuracy = 0.059777778 (25.154 sec)
INFO:tensorflow:loss = 0.2900401, step = 139911 (25.154 sec)
INFO:tensorflow:global_step/sec: 39.2297
INFO:tensorflow:train_accuracy = 0.058666665 (25.448 sec)
INFO:tensorflow:loss = 0.32500568, step = 140911 (25.452 sec)
INFO:tensorflow:global_step/sec: 39.8932
INFO:tensorflow:train_accuracy = 0.058933333 (25.079 sec)
INFO:tensorflow:loss = 0.5762115, step = 141911 (25.075 sec)
INFO:tensorflow:global_step/sec: 39.5285
INFO:tensorflow:train_accuracy = 0.061277777 (25.283 sec)
INFO:tensorflow:loss = 0.30151317, step = 142911 (25.283 sec)
INFO:tensorflow:global_step/sec: 39.9391
INFO:tensorflow:train_accuracy = 0.061095238 (25.054 sec)
INFO:tensorflow:loss = 0.27747443, step = 143911 (2

INFO:tensorflow:train_accuracy = 0.06614286 (27.085 sec)
INFO:tensorflow:loss = 0.3007663, step = 169753 (27.073 sec)
INFO:tensorflow:global_step/sec: 36.6228
INFO:tensorflow:train_accuracy = 0.06666667 (27.313 sec)
INFO:tensorflow:loss = 0.40856463, step = 170753 (27.309 sec)
INFO:tensorflow:global_step/sec: 35.0447
INFO:tensorflow:train_accuracy = 0.06655555 (28.523 sec)
INFO:tensorflow:loss = 0.30192965, step = 171753 (28.527 sec)
INFO:tensorflow:Saving checkpoints for 172280 into results\991\model.ckpt.
INFO:tensorflow:Loss for final step: 0.4711893.
Training complete. Evaluating...
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-06-06T03:24:57Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\991\model.ckpt-172280
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


KeyboardInterrupt: 

In [18]:
import pickle
import gzip
with gzip.open('H:\\JupyterGod\\EQL_Tensorflow-master\\EQL_Tensorflow-master\\data\\F1data_test', 'rb') as filehandle:  
    l = pickle.load(filehandle)

In [38]:
import numpy as np
print(l)

(array([[-0.03238728, -0.1627878 ,  1.3380238 , -0.64751226],
       [ 0.8231169 , -0.45987415,  1.1614982 , -0.9253064 ],
       [-0.97029996, -1.7566586 ,  1.6707381 ,  1.1218562 ],
       ...,
       [ 1.6172212 , -1.3487263 , -0.4985344 , -0.39348963],
       [ 1.9764037 ,  0.4067093 , -0.915228  ,  0.15478812],
       [-1.079934  , -1.3736744 ,  0.4120537 ,  0.3556053 ]],
      dtype=float32), array([[-0.00457749],
       [ 0.18525286],
       [-0.9282876 ],
       ...,
       [-1.1437831 ],
       [ 0.22235489],
       [-0.7301342 ]], dtype=float32))


In [10]:
import pickle
import gzip
with open('H:\\JupyterGod\\EQL_Tensorflow-master\\EQL_Tensorflow-master\\my1.data', 'rb') as filehandle:  
    l = pickle.load(filehandle)

In [11]:
print(l)

[(-1.25974895923783*x_1 + 0.525211334228516*(-0.679548442363739*x_1 - 0.104554362595081)*(0.147878006100655*x_1 + 0.102589040994644) + 0.411604046821594*(-0.578858196735382*x_1 + 0.102627903223038)*(0.415627002716064*x_1 - 0.102811463177204) - 0.551245331764221*(-0.574906229972839*x_1 + 0.0930090546607971)*(0.556529939174652*x_1 - 0.0930221974849701) + 0.30805242061615*(-0.491643577814102*x_1 + 0.0996309071779251)*(-0.189185917377472*x_1 + 0.100450448691845) + 0.421773672103882*(-0.378132939338684*x_1 - 0.102724477648735)*(0.729521691799164*x_1 + 0.103152640163898) - 0.0543379634618759*(-0.27085217833519*x_1 - 0.112603209912777)*(-0.0584261752665043*x_1 - 0.105064980685711) + 0.109128512442112*(0.231077522039413*x_1 + 0.104365952312946)*(0.36739781498909*x_1 + 0.104960896074772) + 0.554951965808868*(0.262664943933487*x_1 + 0.106766879558563)*(0.367512851953506*x_1 + 0.107187800109386) - 0.195080295205116*(0.348738193511963*x_1 + 0.0557493232190609)*(0.472996205091476*x_1 + 0.0557304695

In [5]:
print(l[0])

(-0.00366518293347508*x_1 - 0.00647844227824168*x_10 - 0.00470563096928754*x_11 + 0.00810055917542594*x_12 - 0.00166147174729479*x_13 - 0.004458230399927*x_14 + 0.000562165890414693*x_15 - 0.00497237907824909*x_16 - 0.00616039198109245*x_17 - 0.00124161705239713*x_18 - 0.00146633359257349*x_19 + 0.00556222802233403*x_2 - 0.00721050964589182*x_20 + 0.00047374671891676*x_21 + 0.00493977195913456*x_22 - 0.000780916074447278*x_23 + 0.00148273547662876*x_24 + 0.011922849440436*x_25 + 0.00828363638710626*x_26 - 0.00145262827819*x_27 - 0.00330490005035784*x_28 - 0.00384984769490442*x_29 + 0.00523981900676277*x_3 + 0.00453271793029133*x_30 + 0.000363005263918254*x_31 + 0.00209286766600575*x_32 - 0.0107377538434497*x_33 - 0.00107594467266101*x_34 - 0.00316589355121003*x_35 - 0.00559507262639037*x_36 - 0.00363072392745755*x_37 + 0.00674133134114821*x_38 - 0.000923314806118891*x_39 + 0.00426639217851962*x_4 - 0.00528292896486159*x_5 - 0.00105249373841061*x_6 + 0.00181071958087467*x_7 + 0.00304448

In [4]:
import sympy as sp
#print(l)
expr=l[0]
print(sp.simplify(expr))

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "G:\MyAnaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-73cd032e9495>", line 4, in <module>
    print(sp.simplify(expr))
  File "G:\MyAnaconda\lib\site-packages\sympy\simplify\simplify.py", line 565, in simplify
    _e = cancel(expr)
  File "G:\MyAnaconda\lib\site-packages\sympy\polys\polytools.py", line 6625, in cancel
    c, P, Q = F.cancel(G)
  File "G:\MyAnaconda\lib\site-packages\sympy\polys\polytools.py", line 3693, in cancel
    result = F.cancel(G, include=include)
  File "G:\MyAnaconda\lib\site-packages\sympy\polys\polyclasses.py", line 698, in cancel
    cF, cG, F, G = dmp_cancel(F, G, lev, dom, include=False)
  File "G:\MyAnaconda\lib\site-packages\sympy\polys\euclidtools.py", line 1874, in dmp_cancel
    _, p, q = dmp_inner_gcd(f, g, u, K)
  File "G:\MyAnaconda\lib\site-packages\sympy\polys\euclidtools.py", line 1591, in

KeyboardInterrupt: 

In [1]:
#F2
%run data_utils.py
%run train.py

Using default parameters.
Successfully created train/val data file in data\F2data_train_val.
Successfully created test data file in data\F2data_test.
INFO:tensorflow:Using config: {'_model_dir': 'results\\2', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000023B90FE2A20>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
One train episode equals 50 normal epochs and 1 penalty epoch.
Training complete. Evaluating...
Instr

INFO:tensorflow:Saving dict for global step 91800: eval_accuracy = 0.991, global_step = 91800, loss = 0.008003072
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 91800: results\2\model.ckpt-91800
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-05-24T19:11:06Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from results\2\model.ckpt-91800
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2019-05-24-19:11:07
INFO:tensorflow:Saving dict for global step 91800: eval_accuracy = 0.2652, global_step = 91800, loss = 0.35642365
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 91800: results\2\model.ckpt-91800
Model evaluated. Results:
 {'val_error': 0.008003072, 'complexity': 59, 'extr_error': 0.35642365, 'id': 2}


In [2]:
%run train.py

INFO:tensorflow:Using config: {'_model_dir': 'results\\2', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E9E7943D68>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
One train episode equals 50 normal epochs and 1 penalty epoch.
Training complete. Evaluating...
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-05-24T18:23:28Z
INFO:tensorflow:Graph 

KeyboardInterrupt: 

In [1]:
#1
%run data_utils.py
%run train.py

Using default parameters.
Successfully created train/val data file in data\F1data_train_val.
Successfully created test data file in data\F1data_test.
INFO:tensorflow:Using config: {'_model_dir': 'results\\1', '_tf_random_seed': None, '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': intra_op_parallelism_threads: 1
, '_keep_checkpoint_max': 1, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000002442C56CD30>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
One train episode equals 50 normal epochs and 1 penalty epoch.
Training complete. Evaluating...
Instr

In [27]:
from pybel import *
i=0
for molecule in readfile("sdf","gdb9.sdf"):
    #print(molecule.make3D(forcefield='mmff94', steps=50))
    molcoords = [atom.coords for atom in molecule]
    print([atom.atomicnum for atom in molecule])
    n=[atom.atomicnum for atom in molecule]
    for j in range (0,len(n)):
        if n[j]==1:
            n[j]='H'
        elif n[j]==6:
            n[j]='C'
        elif n[j]==7:
            n[j]='N'
        elif n[j]==8:
            n[j]='O'
        elif n[j]==9:
            n[j]='F'
            
    print(n)
            
    #print(i," ",molecule.formula,molcoords,"\n")
    #print(molecule.atoms.atomicnum)
    
    i=i+1
    if(i==1872):
        mymol=molecule
        mycds=molcoords
    if i>2:
        break
#print(mymol.formula,mycds)
#for i in molcoords:
 #   i=list(molcoords)
l=[list(i) for i in molcoords]
print(l)
#print(map(list,molcoords))

[6, 1, 1, 1, 1]
['C', 'H', 'H', 'H', 'H']
[7, 1, 1, 1]
['N', 'H', 'H', 'H']
[8, 1, 1]
['O', 'H', 'H']
[[-0.0344, 0.9775, 0.0076], [0.0648, 0.0206, 0.0015], [0.8718, 1.3008, 0.0007]]


In [61]:
import numpy as np
def _featurize(mol):
    coordfeat = mycds
    #coordinates = coordfeat._featurize(mol)[0]
    atom_numbers = np.array([atom.atomicnum for atom in mol])
    atom_numbers = np.expand_dims(atom_numbers, axis=1)
    #assert atom_numbers.shape[0] == coordinates.shape[0]
    n_atoms = atom_numbers.shape[0]
    features = np.concatenate([atom_numbers,coordinates], axis=1)
    return np.pad(features, ((0, 20 - n_atoms), (0, 0)), 'constant')
print(_featurize(mymol))

[[6]
 [6]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [76]:
def cds_featurize(mol):
    #N = mol.GetNumAtoms()
    #atom_numbers = np.array([atom.atomicnum for atom in mol])
    #atom_numbers = np.expand_dims(atom_numbers, axis=1)
    #N = atom_numbers.shape[0]
    N=mol.GetNumAtoms()
    print(N)
    coords = np.zeros((N, 3))

    # RDKit stores atomic coordinates in Angstrom. Atomic unit of length is the
    # bohr (1 bohr = 0.529177 Angstrom). Converting units makes gradient calculation
    # consistent with most QM software packages.
    coords_in_bohr = [
        mol.GetConformer(0).GetAtomPosition(i).__idiv__(0.52917721092)
        for i in range(N)
    ]

    for atom in range(N):
        coords[atom, 0] = coords_in_bohr[atom].x
        coords[atom, 1] = coords_in_bohr[atom].y
        coords[atom, 2] = coords_in_bohr[atom].z

    coords = [coords]
    return coords

print(cds_featurize(myrdmol))

2
[array([[-0.03533788,  2.88296618,  0.01965315],
       [ 0.00396842, -0.00736993,  0.00377945]])]


In [34]:
class BPSymmetryFunction(Featurizer):
  """
  Calculate Symmetry Function for each atom in the molecules
  Methods described in https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.98.146401
  """

    def __init__(self, max_atoms):
    self.max_atoms = max_atoms
    def _featurize(self, mol):
    coordfeat = AtomicCoordinates()
    coordinates = coordfeat._featurize(mol)[0]
    atom_numbers = np.array([atom.GetAtomicNum() for atom in mol.GetAtoms()])
    atom_numbers = np.expand_dims(atom_numbers, axis=1)
    assert atom_numbers.shape[0] == coordinates.shape[0]
    n_atoms = atom_numbers.shape[0]
    features = np.concatenate([atom_numbers, coordinates], axis=1)
    return np.pad(features, ((0, self.max_atoms - n_atoms), (0, 0)), 'constant')

IndentationError: unexpected indent (<ipython-input-34-92c5fc456bda>, line 7)

In [54]:
print(molcoords)

[(-0.0029, 1.5099, 0.0087), (0.0261, 0.0033, -0.0375), (0.9423, -0.6551, -0.4568), (0.9228, 1.9263, -0.3915), (-0.862, 1.8785, -0.5648), (-0.1505, 1.8439, 1.0429), (-0.8944, -0.4864, 0.3577)]


In [77]:
from rdkit import Chem
import rdkit.Chem.rdMolDescriptors as abc
i=0
suppl = Chem.SDMolSupplier('gdb9.sdf')
for mol in suppl:
    if mol is None: continue
    print(abc.CalcMolFormula(mol),mol.GetNumAtoms())
    if i==6:
        myrdmol=mol
    if i>10:
        break
    i=i+1
abc.CalcMolFormula(myrdmol)

CH4 1
H3N 1
H2O 1
C2H2 2
CHN 2
CH2O 2
C2H6 2
CH4O 2
C3H4 3
C2H3N 3
C2H4O 3
CH3NO 3


'C2H6'

In [4]:
# USE THIS CELL 1
# FINAL
"""
from pybel import *
i=0
for molecule in readfile("sdf","gdb9.sdf"):
    #print(molecule.make3D(forcefield='mmff94', steps=50))
    molcoords = [atom.coords for atom in molecule]
    print(molecule.formula,molcoords,"\n")
    i=i+1
    if(i==7):
        mymol=molecule
        mycds=molcoords
    if i>10:
        break
print(mymol.formula,mycds)

"""
import rdkit
def cds_featurize(mol):
    #N = mol.GetNumAtoms()
    #atom_numbers = np.array([atom.atomicnum for atom in mol])
    #atom_numbers = np.expand_dims(atom_numbers, axis=1)
    #N = atom_numbers.shape[0]
    
    N=mol.GetNumAtoms()
    #print(N)
    coords = np.zeros((N, 3))

    # RDKit stores atomic coordinates in Angstrom. Atomic unit of length is the
    # bohr (1 bohr = 0.529177 Angstrom). Converting units makes gradient calculation
    # consistent with most QM software packages.
    coords_in_bohr = [
        mol.GetConformer(0).GetAtomPosition(i).__idiv__(0.52917721092)
        for i in range(N)
    ]

    for atom in range(N):
        coords[atom, 0] = coords_in_bohr[atom].x
        coords[atom, 1] = coords_in_bohr[atom].y
        coords[atom, 2] = coords_in_bohr[atom].z

    coords = [coords]
    return coords

#####################
import numpy as np
#from rdkit.Chem.rdchem.Atom import GetAtomicNum
def _featurize(mol):
    #coordfeat = mycds
    coordinates = cds_featurize(mol)[0]
    atom_numbers = np.array([rdkit.Chem.rdchem.Atom.GetMass(atom) for atom in mol.GetAtoms()])
    atom_numbers = np.expand_dims(atom_numbers, axis=1)
    assert atom_numbers.shape[0] == coordinates.shape[0]
    n_atoms = atom_numbers.shape[0]
    features = np.concatenate([atom_numbers,coordinates], axis=1)
    return np.pad(features, ((0, 9 - n_atoms), (0, 0)), 'constant')
######################

from rdkit import Chem
import rdkit.Chem.rdMolDescriptors as abc
from rdkit import Chem
import rdkit
import rdkit.Chem.rdMolDescriptors as abc
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.AllChem import ComputeMolVolume
import numpy
i=0
max_atoms=9
molecule_list=[]
coords_list=[]
suppl = Chem.SDMolSupplier('gdb9.sdf')
for mol in suppl:
    if mol is None: continue
    molecule_list.append(mol)
    coords_list.append(_featurize(mol))
    AllChem.EmbedMolecule(mol)
    print(ComputeMolVolume(mol,confId=0))
    
 
    
    #print(abc.CalcMolFormula(mol),mol.GetNumAtoms())
    print(Chem.MolToSmiles(mol))
    if i==6:
        myrdmol=mol
        
    if i>10:
        break
    i=i+1
#print(abc.CalcMolFormula(myrdmol))
#print(cds_featurize(myrdmol))
#print(_featurize(myrdmol))

    






31.096000000000007
C
26.296000000000006
N
20.424000000000007
O
45.03200000000001
C#C
41.54400000000001
C#N
38.464000000000006
C=O
48.40800000000001
CC
40.20000000000001
CO
61.84800000000001
C#CC
58.152000000000015
CC#N
55.73600000000001
CC=O
52.44000000000001
NC=O


In [34]:
# USE THIS CELL 2
# FINAL
c_final=np.array(coords_list)
print(c_final.shape)

(133247, 9, 4)


In [35]:
print(coords_list[4])
print(c_final[4])

[[ 1.20110000e+01 -2.51333575e-02  2.14011484e+00  1.56847268e-02]
 [ 1.40070000e+01  4.34637009e-03 -3.62827416e-02  3.59047964e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
[[ 1.20110000e+01 -2.51333575e-02  2.14011484e+00  1.56847268e-02]
 [ 1.40070000e+01  4.34637009e-03 -3.62827416e-02  3.59047964e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000

In [36]:
z=[]
for i in range(0,len(coords_list)):
    c=np.ravel(c_final[i],order='C')
    z.append(c)
print(z[4])

[[ 1.20110000e+01 -2.51333575e-02  2.14011484e+00  1.56847268e-02]
 [ 1.40070000e+01  4.34637009e-03 -3.62827416e-02  3.59047964e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [38]:
print(z[3])
print(c_final[3])

[12.011       1.13289081  0.          1.88972612 12.011      -1.13289081
  0.          1.88972612  0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.        ]
[[12.011       1.13289081  0.          1.88972612]
 [12.011      -1.13289081  0.          1.88972612]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [97]:
print(c_final[1000])

[[ 6.00000000e+00 -9.63760324e-03  2.73159911e+00 -2.64561657e-03]
 [ 7.00000000e+00  2.38105492e-02  3.21253441e-03 -7.04867844e-02]
 [ 6.00000000e+00  1.13005622e-01 -1.53899296e+00 -2.20171991e+00]
 [ 6.00000000e+00  1.19430691e-01 -3.96294466e+00 -1.41540487e+00]
 [ 7.00000000e+00  3.45819881e-02 -3.91966993e+00  1.21282623e+00]
 [ 6.00000000e+00 -2.64561657e-02 -1.45924651e+00  2.11819401e+00]
 [ 8.00000000e+00 -1.05068773e-01 -7.34347572e-01  4.30158358e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [91]:
from rdkit import Chem
import rdkit.Chem.rdMolDescriptors as abc
s = Chem.SDMolSupplier('gdb9.sdf')
m=-1
for mole in s:
    if mole is None: continue
    m=max(m,mole.GetNumAtoms())
print(m)

9


In [2]:
from rdkit.Chem import PandasTools
from rdkit import RDConfig
import os
import pandas as pd
sdfFile = os.path.join('gdb9.sdf')
frame = PandasTools.LoadSDF(sdfFile)


In [36]:
list(frame.columns.values)
k=1
i=1000*k
m=0
missing=[]
for j in range (0,frame.shape[0]):
    s=frame.iloc[j].ID
    #print(s)
    s=s[4:]
    s=int(s)
    #print("H ",s," M ",m)
    if (s-m)>1:
        for p in range (m+1,s):
            print(p)
            missing.append(p)
        m=s
    else:
        m=m+1
#frame.isnull().sum().sum()

317
1150
1898
2003
2007
2010
2013
2018
2423
2424
6567
6593
6594
6598
6601
6603
8046
8047
8057
8062
8065
8340
8344
8349
8356
8359
8364
8367
8393
8396
8400
8403
8491
8495
8506
8531
8535
8587
8595
8600
8602
10883
10884
11639
11640
11646
11652
11654
11659
11668
11672
14183
14187
14188
14357
14360
14367
14368
14369
14449
14455
14456
17146
17157
17158
17166
17167
17175
17176
17186
17187
17260
17688
17692
17694
17720
17727
17728
17732
22418
22432
24464
24469
33287
33291
33721
33724
33751
33761
33762
34134
34138
34144
34153
34154
34155
34783
34788
34789
34794
35339
35346
36168
36169
36178
36179
36596
36602
36837
36840
36843
37150
37151
37159
37163
37164
37697
37700
37715
37716
37740
37741
37743
37749
37813
37814
37818
37819
37825
37826
37827
37832
37835
37840
37868
37872
37894
37895
37896
37900
37902
38190
38195
38210
38211
38222
38223
38241
38242
38267
38268
38269
38270
38271
38276
38277
38279
38470
38474
38475
38476
38477
38584
38586
38588
38589
38591
39626
39629
39632
40471
40479
40480
4048

In [42]:
print(len(missing))
print(frame.shape)
print(frame.iloc[316])

638
(133247, 2)
ID                                                 gdb_318
ROMol    <img src="data:image/png;base64,iVBORw0KGgoAAA...
Name: 317, dtype: object


In [48]:
import pandas as pd
df=pd.read_csv('gdb9.csv')
import numpy as np
df=df.drop(np.array(missing)-1,axis=0)
print(df.shape)
y=np.array(df.iloc[:,1:4])
list(df.columns.values)
k=1
i=1000*k
m=0
missing_df=[]
for j in range (0,df.shape[0]):
    s=df.iloc[j].mol_id
    #print(s)
    s=s[4:]
    s=int(s)
    #print("H ",s," M ",m)
    if (s-m)>1:
        for p in range (m+1,s):
            print(p)
            missing_df.append(p)
        m=s
    else:
        m=m+1

(133247, 20)
317
1150
1898
2003
2007
2010
2013
2018
2423
2424
6567
6593
6594
6598
6601
6603
8046
8047
8057
8062
8065
8340
8344
8349
8356
8359
8364
8367
8393
8396
8400
8403
8491
8495
8506
8531
8535
8587
8595
8600
8602
10883
10884
11639
11640
11646
11652
11654
11659
11668
11672
14183
14187
14188
14357
14360
14367
14368
14369
14449
14455
14456
17146
17157
17158
17166
17167
17175
17176
17186
17187
17260
17688
17692
17694
17720
17727
17728
17732
22418
22432
24464
24469
33287
33291
33721
33724
33751
33761
33762
34134
34138
34144
34153
34154
34155
34783
34788
34789
34794
35339
35346
36168
36169
36178
36179
36596
36602
36837
36840
36843
37150
37151
37159
37163
37164
37697
37700
37715
37716
37740
37741
37743
37749
37813
37814
37818
37819
37825
37826
37827
37832
37835
37840
37868
37872
37894
37895
37896
37900
37902
38190
38195
38210
38211
38222
38223
38241
38242
38267
38268
38269
38270
38271
38276
38277
38279
38470
38474
38475
38476
38477
38584
38586
38588
38589
38591
39626
39629
39632
40471
404

In [49]:
df.iloc[316]
print(missing==missing_df)

True


In [50]:
import pickle
with open("missing", "wb") as fp: 
    pickle.dump(missing, fp)

In [15]:
import os
path=os.path.abspath("H:/JupyterGod/EQL_Tensorflow-master/EQL_Tensorflow-master/qdb9.sdf")
print(path)

H:\JupyterGod\EQL_Tensorflow-master\EQL_Tensorflow-master\qdb9.sdf


In [18]:
import glob
for x in glob.glob('*.sdf'):
    i=x
    print(x)

gdb9.sdf


In [11]:
import gzip
import pickle
with gzip.open('H:\\JupyterGod\\EQL_Tensorflow-master\\EQL_Tensorflow-master\\data\\F99data', 'rb') as filehandle:  
        X = pickle.load(filehandle)
print(X[133000:133003])
k=0
for k in range (0,9):
    X[:,k*4+1:k*4+4]*=10
print("___________________________________________________________________")
print(X[133000:133003])

[[ 1.89980000e+01  5.66917837e-03  1.24721924e-01 -1.68185625e-01
   1.20110000e+01 -7.06757571e-02  2.65808877e+00 -1.05824663e-02
   1.89980000e+01  2.32152854e+00  3.49372566e+00 -1.74043776e-01
   1.89980000e+01 -1.30920226e+00  3.50581991e+00 -2.05583305e+00
   1.20110000e+01 -1.33641432e+00  3.53227607e+00  2.40259779e+00
   1.20110000e+01  2.34326039e-02  2.60083007e+00  4.78081812e+00
   1.20110000e+01 -1.29805287e+00  3.51507956e+00  7.20968311e+00
   1.20110000e+01 -3.34481524e-02  2.64920705e+00  9.49814145e+00
   1.20110000e+01  1.04180601e+00  1.91202489e+00  1.13572540e+01]
 [ 1.89980000e+01  1.30391103e-02  1.19997609e-01 -1.45319939e-01
   1.20110000e+01 -6.12271264e-02  2.65241959e+00  1.88972612e-04
   1.89980000e+01  2.33022128e+00  3.48805648e+00 -1.49288364e-01
   1.89980000e+01 -1.29351753e+00  3.49769408e+00 -2.04619545e+00
   1.20110000e+01 -1.33773712e+00  3.53359888e+00  2.40807800e+00
   1.20110000e+01  2.28656861e-02  2.59894034e+00  4.78403066e+00
   1.2011

In [18]:
print(np.reciprocal(X[0]))

[ 0.08325701 -4.16674969  0.04873616  6.61471514         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf]


G:\MyAnaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.


In [27]:
abcd=np.array([1,2,3,4])
xyzf=np.array([7,2,3,4])
abcd*xyzf

array([ 7,  4,  9, 16])